# Generated by Django 5.1.4 on 2025-04-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarDekho_app', '0002_rename_name_carlist_car_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carlist',
            old_name='car_name',
            new_name='name',
        ),
    ]
