# Generated by Django 5.1.4 on 2025-04-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarDekho_app', '0003_rename_car_name_carlist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carlist',
            old_name='name',
            new_name='car_name',
        ),
    ]
