# Generated by Django 5.2 on 2025-04-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarDekho_app', '0004_rename_name_carlist_car_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carlist',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
