# Generated by Django 5.1.4 on 2025-05-02 18:06

import CarDekho_app.models.car_list
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarDekho_app', '0005_carlist_chassis_number_carlist_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowroomList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showroom_name', models.CharField(max_length=100)),
                ('showroom_address', models.CharField(max_length=100)),
                ('showroom_contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='carlist',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[CarDekho_app.models.car_list.alphanumeric]),
        ),
    ]
