# Generated by Django 5.1.4 on 2025-05-03 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarDekho_app', '0006_showroomlist_alter_carlist_chassis_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='shworoom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Showrooms', to='CarDekho_app.showroomlist'),
        ),
    ]
